version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.1.2
    user: 0:0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker-1:
    image: docker.io/bitnami/spark:3.1.2
    user: 0:0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:3.1.2
    user: 0:0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    command: pyspark --master spark://spark-master:7077 --packages graphframes:graphframes:0.8.1-spark3.0-s_2.12 --repositories https://repos.spark-packages.org/
    container_name: ag-spark-demo-jupyter
    user: 0:0
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "8088:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab --ip 0.0.0.0 --ServerApp.token='' -y --no-browser --allow-root --ServerApp.notebook_dir="/root/work"

  ag:
    image: franzinc/agraph:v7.1.0
    container_name: ag-spark-demo-ag
    ports:
      - "10015:10035"
    shm_size: 1g
    environment:
      - AGRAPH_SUPER_USER=test
      - AGRAPH_SUPER_PASSWORD=xyzzy
